export const LESSON8_EXPECTED_ERRORS = [
  ['LINK_CHORD_COUNT', 0], ['LINK_MISSING', 0],
  ['HARMONIC_PARALLEL_FIFTHS', 2],
  ['MELODIC_FORBIDDEN_INTERVAL', 4], ['HARMONIC_CONTRARY_OCTAVES', 4],
  ['LINK_LEADING_TONE_SOPRANO', 6], ['LINK_UNASSIGNED', 8],
  ['HARMONIC_SIMULTANEOUS_LEAPS', 10],
];
